name: maze

permissions:
  contents: write

on:
  push:
    tags:
      - "*.*.*"
      - "test-maze-*"

jobs:
  Web:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Build
        working-directory: ./day-5
        run: |
          set -x
          curl -L -o calm.tgz https://github.com/VitoVan/calm/releases/download/test-calm-013-06/calm.tgz
          mkdir calm
          tar xvf calm.tgz --directory=calm
          ls -lah calm
          export PATH=$PATH:$(pwd)/calm/
          export APP_NAME=Maze
          # export REBUILD_WASM_P=yes
          calm publish-web
          ls -lah .
          zip -r -9 ${APP_NAME}-web.zip ./web
          cp *.zip ../
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          draft: true
          files: |
            *-web.zip
  Linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Build
        working-directory: ./day-5
        run: |
          set -x
          curl -L -o calm.tgz https://github.com/VitoVan/calm/releases/download/test-calm-013-06/calm.tgz
          mkdir calm
          tar xvf calm.tgz --directory=calm
          ls -lah calm
          export PATH=$PATH:$(pwd)/calm/
          export APP_NAME=Maze
          export APP_ICON="$(pwd)/images/app.png"
          calm publish
          ls -lah .
          mv *.AppImage ../
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          draft: true
          files: |
            *.AppImage
  macOS:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13]

    env:
      CI_MATRIX_OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Build
        working-directory: ./day-5
        run: |
          set -x
          export OS_SUBFIX=".${CI_MATRIX_OS}"
          curl -L -o calm.dmg https://github.com/VitoVan/calm/releases/download/test-calm-013-06/calm${OS_SUBFIX}.dmg
          hdiutil attach calm.dmg
          cp -R "/Volumes/Calm - CALM/Calm.app/Contents/MacOS/" calm
          ls -lah calm
          rm calm.dmg
          export PATH=$PATH:$(pwd)/calm/
          export APP_ICON="$(pwd)/images/app.icns"
          export DMG_ICON="$(pwd)/images/dmg.icns"
          export APP_VERSION=0.0.1
          export APP_ID=com.vitovan.maze
          export APP_NAME=Maze
          calm publish
          ls -lah .
          mv *.dmg ../Maze${OS_SUBFIX}.dmg
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          draft: true
          files: |
            *.dmg
  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2

      - name: Build
        working-directory: ./day-5
        shell: msys2 {0}
        run: |
          set -x
          pacman -S --noconfirm --needed unzip
          curl -L -o calm.zip https://github.com/VitoVan/calm/releases/download/test-calm-013-06/calm.zip
          unzip calm.zip -d calm
          ls -lah calm
          export PATH=$PATH:$(pwd)/calm/
          export APP_ICON="$(pwd)/images/app.ico"
          export APP_NAME=Maze
          calm publish
          mv ./*-Installer.exe ../Maze.exe
          ls -lah .
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          draft: true
          files: |
            *.exe
